server:
  port: ${service_port:1001}

spring:  
  application:
    name: mvp-sample-springboot

  profiles:
    active: ${profile:default}
    include: common
    
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db_host:169.56.70.197}:${db_port:3306}/${db_name:msa}?useUnicode=true&characterEncoding=utf-8
    username: ${db_user:msa}
    password: ${db_pw:happy@cloud}
    sql-script-encoding: utf-8
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1
    
#logging
logging:
   config:
   pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}" 
   level: 
      org.springframework: warn
      com.springboot.microservices.sample: debug
  
mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: com.springboot.microservices.sample.model

